version: 2

build:
   os: ubuntu-20.04
   tools:
      python: "3.7"

python:
   version: 3.7
   install:
      - requirements: docs/requirements.txt
      - method: setuptools
        path: .

formats: []
