version: 2

build:
   os: ubuntu-22.04
   tools:
      python: "3.7"

python:
   install:
      - requirements: docs/requirements.txt
      - method: setuptools
        path: .
      
sphinx:
  configuration: docs/conf.py

formats: []
