package:
  name: pygsd
  version: 0.3.2

source:
  path: ./

requirements:
  host:
    - pip
    - python {{ environ.get('PYTHON_VERSION') }}

  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
    - pytorch-scatter
    - pytorch-sparse
    - numpy
    - requests
    - scikit-learn
    - pyg

build:
  string: py{{ environ.get('PYTHON_VERSION').replace('.', '') }}_torch_{{ environ['TORCH_VERSION'] }}_{{ environ['CUDA_VERSION'] }}
  script: pip install .

test:
  imports:
    - torch_scatter
    - torch_sparse
    - torch_geometric
    - torch_geometric_signed_directed
    - torch_geometric_signed_directed.nn
    - torch_geometric_signed_directed.data
    - torch_geometric_signed_directed.utils

about:
  home: https://github.com/SherylHYX/pytorch_geometric_signed_directed
  license: MIT
  summary: A signed/directed graph neural network extension library for PyTorch Geometric. 